name: Microsoft Learn General Formatting
on:
  # Trigger the workflow on push or pull request
  pull_request:
    branches: 
      - main
      - master
      
jobs:
  asses-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Add Label and thanks comment to Pull request
        uses: actions/github-script@v6
        with:
          script: |
            const issueAuthor = context.payload.sender.login
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-review']
            })
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `👋 Thanks for reporting @${ issueAuthor }! We will review the pull request and get back to you soon.`
            })
  format-first-two-lines:
    needs: asses-pull-request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run Format First two lines function
        run: python markdown_formatter.py --dir './docs/dev/tutorials/' --func 'first_two_lines'
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: fix first two lines formatting
      - name: Leave a comment
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `We have automatically fixed some issues in the first two lines of your exercises.
                     Please follow the contributing guide found [here](https://github.com/leestott/microsoft-cloud-pr/blob/main/CONTRIBUTING.md#general-guidance) to avoid this in the future.
                     Run the following command in your terminal to view these changes **git pull**.`
            })
  add-empty-last-line:
    needs: format-first-two-lines
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run Add empty last line
        run: python markdown_formatter.py --dir './docs/dev/tutorials/' --func 'add_empty_last_line'
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: fix last line formatting
      - name: Leave a comment
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `We have automatically added an empty line to the end of your exercises.
                     Please follow the contributing guide found [here](https://github.com/leestott/microsoft-cloud-pr/blob/main/CONTRIBUTING.md#general-guidance) to avoid this in the future.
                     Run the following command in your terminal to view these changes **git pull**.`
            })
  replace-all-with-select:
    needs: add-empty-last-line
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run Replace with select
        run: python markdown_formatter.py --dir './docs/dev/tutorials/' --func 'replace_all_with_select'
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: fix replace all with select
      - name: Leave a comment
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `We have automatically replaced the words choose and click with select in your exercises.
                     Please follow the contributing guide found [here](https://github.com/leestott/microsoft-cloud-pr/blob/main/CONTRIBUTING.md#general-guidance) to avoid this in the future.
                     Run the following command in your terminal to view these changes **git pull**.`
            })
  remove-links-locale:
    needs: replace-all-with-select
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run Remove links locale
        run: python markdown_formatter.py --dir './docs/dev/tutorials/' --func 'remove_links_locale'
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: fix remove links locale
      - name: Leave a comment
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `We have automatically removed the locale (ex. en-us) from links in your exercises.
                     Please follow the contributing guide found [here](https://github.com/leestott/microsoft-cloud-pr/blob/main/CONTRIBUTING.md#general-guidance) to avoid this in the future.
                     Run the following command in your terminal to view these changes **git pull**.`
            })
  remove-relative-links:
    needs: remove-links-locale
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Run Remove relative links
        run: python markdown_formatter.py --dir './docs/dev/tutorials/' --func 'remove_relative_links'
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: fix remove relative links
      - name: Leave a comment
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `We have automatically removed learn.microsoft.com from relative links in your exercises.
                     Please follow the contributing guide found [here](https://github.com/leestott/microsoft-cloud-pr/blob/main/CONTRIBUTING.md#general-guidance) to avoid this in the future.
                     Run the following command in your terminal to view these changes **git pull**.`
            })
